# Generated by Django 3.1 on 2021-06-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210630_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.IntegerField(default=0),
        ),
    ]
