# Generated by Django 3.1 on 2021-07-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210704_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='platform',
        ),
    ]
